pichayon/web/forms/accounts.py
from wtforms import Form
from wtforms import fields
from wtforms import validators

from flask_wtf import FlaskForm


class AccountForm(FlaskForm):
    first_name = fields.StringField(
        "First Name", validators=[validators.InputRequired(), validators.Length(min=3)]
    )
    last_name = fields.StringField(
        "Last Name", validators=[validators.InputRequired(), validators.Length(min=3)]
    )
    first_name_th = fields.StringField(
        "First Name (Thai)",
        validators=[validators.InputRequired(), validators.Length(min=3)],
    )
    last_name_th = fields.StringField(
        "Last Name (Thai)",
        validators=[validators.InputRequired(), validators.Length(min=3)],
    )
    id_card_number = fields.StringField(
        "ID Card Number",
        validators=[validators.Optional()],
    )

pichayon/web/views/accounts.py
import datetime

from flask import (
    Blueprint,
    current_app,
    render_template,
    url_for,
    redirect,
    request,
    session,
)

from flask_login import login_user, logout_user, login_required, current_user
from pichayon import models
from pichayon.web.client.pichayon_client import pichayon_client

from .. import oauth2
from .. import forms

module = Blueprint("accounts", __name__)


def get_user_and_remember():
    client = oauth2.oauth2_client
    result = client.principal.get("me")
    # print('got: ', result.json())
    data = result.json()

    user = models.User.objects(username=data.get("username", "")).first()
    if not user:
        user = models.User(
            id=data.get("id"),
            first_name=data.get("first_name"),
            last_name=data.get("last_name"),
            email=data.get("email"),
            username=data.get("username"),
            status="active",
        )
        roles = []
        for role in ["student", "lecturer", "staff"]:
            if role in data.get("roles", []):
                roles.append(role)

        user.save()

    if user:
        login_user(user, remember=True)


@module.route("/login", methods=("GET", "POST"))
def login():
    if current_user.is_authenticated:
        return redirect(url_for("dashboard.index"))

    if "next" in request.args:
        session["next"] = request.args.get("next", None)

    oauth_clients = current_app.extensions["authlib.integrations.flask_client"]._clients

    return render_template("/accounts/login.html", oauth_clients=oauth_clients)


@module.route("/login/<name>")
def login_oauth(name):
    client = oauth2.oauth2_client

    scheme = request.environ.get("HTTP_X_FORWARDED_PROTO", "http")
    redirect_uri = url_for(
        "accounts.authorized_oauth", name=name, _external=True, _scheme=scheme
    )
    response = None
    if name == "google":
        response = client.google.authorize_redirect(redirect_uri)
    elif name == "facebook":
        response = client.facebook.authorize_redirect(redirect_uri)
    elif name == "line":
        response = client.line.authorize_redirect(redirect_uri)

    elif name == "psu":
        response = client.psu.authorize_redirect(redirect_uri)
    elif name == "engpsu":
        response = client.engpsu.authorize_redirect(redirect_uri)
    return response


@module.route("/auth/<name>")
def authorized_oauth(name):
    client = oauth2.oauth2_client
    remote = None
    try:
        if name == "google":
            remote = client.google
        elif name == "facebook":
            remote = client.facebook
        elif name == "line":
            remote = client.line
        elif name == "psu":
            remote = client.psu
        elif name == "engpsu":
            remote = client.engpsu

        token = remote.authorize_access_token()

    except Exception as e:
        print("autorize access error =>", e)
        return redirect(url_for("accounts.login"))

    session["oauth_provider"] = name
    return oauth2.handle_authorized_oauth2(remote, token)


@module.route("/logout")
@login_required
def logout():
    name = session.get("oauth_provider")
    logout_user()
    session.clear()

    client = oauth2.oauth2_client
    remote = None
    logout_url = None
    if name == "google":
        remote = client.google
        logout_url = f"{ remote.server_metadata.get('end_session_endpoint') }?redirect={ request.scheme }://{ request.host }"
    elif name == "facebook":
        remote = client.facebook
    elif name == "line":
        remote = client.line
    elif name == "psu":
        remote = client.psu
        logout_url = f"{ remote.server_metadata.get('end_session_endpoint') }"
        if not logout_url:
            logout_url = current_app.config.get("PSU_END_SESSION")
    elif name == "engpsu":
        remote = client.engpsu

    if logout_url:
        return redirect(logout_url)

    return redirect(url_for("site.index"))


@module.route("/accounts")
@login_required
def index():
    user = current_user
    if request.args.get("user"):
        user_id = request.args.get("user")
        user = models.User.objects.get(id=user_id)
    return render_template("/accounts/index.html", user=user)


@module.route("/accounts/edit-profile", methods=["GET", "POST"])
@login_required
def edit_profile():
    form = forms.accounts.AccountForm(
        obj=current_user,
    )
    if not form.validate_on_submit():
        return render_template("/accounts/edit-profile.html", form=form)

    user = current_user._get_current_object()
    user.first_name = form.first_name.data
    user.last_name = form.last_name.data
    user.first_name_th = form.first_name_th.data
    user.last_name_th = form.last_name_th.data
    user.id_card_number = form.id_card_number.data
    if not user.gave_informations:
        user.gave_informations = True
    user.save()

    return redirect(url_for("accounts.index"))


@module.route(
    "/accounts/identities/add", methods=["GET", "POST"], defaults={"index": -1}
)
@module.route("/accounts/identities/<int:index>/edit", methods=["GET", "POST"])
@login_required
def add_or_edit_identity(index):
    user = current_user

    form = forms.admin.users.IdentityForm()
    if request.method == "GET" and index >= 0:
        form = forms.admin.users.IdentityForm(obj=user.identities[index])

    if not form.validate_on_submit():
        return render_template(
            "administration/users/add-edit-identity.html",
            form=form,
        )

    identity = models.Identity()
    if index >= 0:
        identity = user.identities[index]

    form.populate_obj(identity)
    identity.added_with = "web"
    identity.added_by = str(current_user.id)
    identity.updated_date = datetime.datetime.now()

    if index < 0:
        is_found = False
        for idr in user.identities:
            if idr.identifier == form.identifier.data:
                is_found = True
                break
        if not is_found:
            user.identities.append(identity)

    user.save()

    pichayon_client.update_member(user=user)

    return redirect(url_for("accounts.index"))

pichayon/web/templates/accounts/edit-profile.html
{% extends '/accounts/index.html' %}
{% import '/base/error-handler.html' as eh %}
{% import '/base/html-renderer.html' as renderer %}

{% block breadcrumbs %}
{{ super() }}
<i class="right angle icon divider"></i>
<div class="active section">Edit Profile</div>
{% endblock %}

{% block content %}
<div class="ui content">
  <div class="ui segment">
    <h2>Profile</h2>
    <form method="POST" class="ui form">
      {{ form.csrf_token }}
      <div class="two fields">
        {{ renderer.render_field(form.first_name) }}
        {{ renderer.render_field(form.last_name) }}
      </div>
      <div class="two fields">
        {{ renderer.render_field(form.first_name_th) }}
        {{ renderer.render_field(form.last_name_th) }}
      </div>
      <div class="two fields">
        {{ renderer.render_field(form.id_card_number) }}
      </div>

      <button name="create" type="submit" class="ui primary button">Confirm</button>
    </form>
  </div>
</div>

<div class="row">
  <div class="col s12">
  </div>
</div>

{% endblock %}

pichayon/web/templates/accounts/index.html
{% extends '/base/default-dashboard.html' %}

{% block dashboard_title %}
Profile
{% endblock %}

{% block breadcrumbs %}
<a href="{{ url_for('accounts.index') }}" class="section">Accounts</a>
{% endblock %}


{% block content %}
<div class="ui segment">
  <h2 class="ui header">Profile
{% if current_user == user or not request.args.get('user')%}
   <a class="btn-floating btn-large waves-effect waves-light" href="{{ url_for('accounts.edit_profile') }}" title='Edit profile.'><i class="edit icon"></i></a>
   {% endif %}
  </h2>
  <div class="ui grid two column">
    <div class="column">
      {{ user.username }}
    </div>
    <div class="column">
      {{ user.roles[-1] }}
    </div>
    <div class="column">
      {{ user.id_card_number }}
    </div>
    <div class="column">
      {{ user.email }}
    </div>
    <div class="column">
      {{ user.first_name }}
    </div>
    <div class="column">
      {{ user.last_name }}
    </div>
    <div class="column">
      {{ user.first_name_th }}
    </div>
    <div class="column">
      {{ user.last_name_th }}
    </div>
  </div>
</div>

<div class="ui segment">
  <h2 class="ui header">Indentity</h2>
    {% if "admin" in current_user.roles %}
      <a class="ui button primary" href="{{ url_for('administration.users.add_or_edit_identity', user_id=user.id) }}">Add</a>
    {% elif current_user.id == user.id %}
      <a class="ui button primary" href="{{ url_for('accounts.add_or_edit_identity', user_id=user.id) }}">Add</a>
    {% endif %}
    <table class="ui selectable celled table">
      <thead>
        <tr>
          <th>Identifier</th>
          <th>Type</th>
          <th>Status</th>
          <th>Created Date</th>
          <th>Updated Date</th>
          <th>Operation</th>
        </tr>
      </thead>
      <tbody>
	      {% for identity in user.identities %}
	{% set rfid = identity.identifier %}
        <tr>
          <td>{{ '*' * rfid[:-3] | length + rfid[-3:] }}</td>
          <td>{{ identity.type }}</td>
          <td>{{ identity.status }}</td>
          <td>{{ identity.created_date }}</td>
          <td>{{ identity.updated_date }}</td>
          <td>
            <a class="ui button primary" href="{{ url_for('accounts.add_or_edit_identity', user_id=user.id, index=loop.index-1 ) }}">Edit</a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
</div>
{% endblock %}

pichayon/web/templates/accounts/login.html
{% extends "/base/default-page.html" %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="ui middle aligned center aligned grid" style="height: 500px">
  <div class="column">
    <h2 class="ui image header" style="font-size: 3em;">
      <i class="ui icon vihara big" ></i> <br/>
      {# <img src="{{ url_for('static', filename='images/lotus-full-500px.png') }}" width="200px"> #}
      <div class="content">
        Login
      </div>
    </h2>
    <div>
      <div class="ui large vertical buttons" >
{% if 'psu' in oauth_clients %}
    	  <div class="row" style="padding: 10px;">
          <div class="column header" style="text-align: left;">
            <h3>{{ "For PSU" }}</h3>
          </div>
        </div>
        <div class="row" style="padding-top: 5px;">
          <a class="ui labeled icon button primary huge" href="{{ url_for('accounts.login_oauth', name='psu') }}">
            <i class="user icon"></i>
            {{ "PSU Passport" }}
          </a>
        </div>
{% endif %}
{% if 'engpsu' in oauth_clients %}
        <div class="row" style="padding: 10px;">
          <div class="column header" style="text-align: left;">
            <h3>{{ "For PSU Engineering Faculty Member" }}</h3>
          </div>
        </div>
        <div class="row" style="padding-top: 5px;">
          <a class="ui labeled icon button primary huge" href="{{ url_for('accounts.login_oauth', name='engpsu') }}">
            <i class="user icon"></i>
            {{ "PSU Passport by Eng" }}
          </a>
	      </div>
{% endif %}
{% if 'google' in oauth_clients %}
        <div class="row" style="padding: 10px;">
          <div class="column header" style="text-align: left;">
            <h3>{{ "For Participant" }}</h3>
          </div>
        </div>
        <div class="row" style="padding-top: 5px;">
          <a class="ui  labeled icon red button huge" href="{{ url_for('accounts.login_oauth', name='google') }}">
            <i class="google icon"></i>
            {{ "Google" }}
          </a>
        </div>
{% endif %}


      </div>
    </div>
  </div>
</div>


{% endblock %}