pichayon/web/views/accounts.py
import datetime

from flask import (
    Blueprint,
    current_app,
    render_template,
    url_for,
    redirect,
    request,
    session,
)

from flask_login import login_user, logout_user, login_required, current_user
from pichayon import models
from pichayon.web.client.pichayon_client import pichayon_client

from .. import oauth2
from .. import forms

module = Blueprint("accounts", __name__)


def get_user_and_remember():
    client = oauth2.oauth2_client
    result = client.principal.get("me")
    # print('got: ', result.json())
    data = result.json()

    user = models.User.objects(username=data.get("username", "")).first()
    if not user:
        user = models.User(
            id=data.get("id"),
            first_name=data.get("first_name"),
            last_name=data.get("last_name"),
            email=data.get("email"),
            username=data.get("username"),
            status="active",
        )
        roles = []
        for role in ["student", "lecturer", "staff"]:
            if role in data.get("roles", []):
                roles.append(role)

        user.save()

    if user:
        login_user(user, remember=True)


@module.route("/login", methods=("GET", "POST"))
def login():
    if current_user.is_authenticated:
        return redirect(url_for("dashboard.index"))

    if "next" in request.args:
        session["next"] = request.args.get("next", None)

    oauth_clients = current_app.extensions["authlib.integrations.flask_client"]._clients

    return render_template("/accounts/login.html", oauth_clients=oauth_clients)


@module.route("/login/<name>")
def login_oauth(name):
    client = oauth2.oauth2_client

    scheme = request.environ.get("HTTP_X_FORWARDED_PROTO", "http")
    redirect_uri = url_for(
        "accounts.authorized_oauth", name=name, _external=True, _scheme=scheme
    )
    response = None
    if name == "google":
        response = client.google.authorize_redirect(redirect_uri)
    elif name == "facebook":
        response = client.facebook.authorize_redirect(redirect_uri)
    elif name == "line":
        response = client.line.authorize_redirect(redirect_uri)

    elif name == "psu":
        response = client.psu.authorize_redirect(redirect_uri)
    elif name == "engpsu":
        response = client.engpsu.authorize_redirect(redirect_uri)
    return response


@module.route("/auth/<name>")
def authorized_oauth(name):
    client = oauth2.oauth2_client
    remote = None
    try:
        if name == "google":
            remote = client.google
        elif name == "facebook":
            remote = client.facebook
        elif name == "line":
            remote = client.line
        elif name == "psu":
            remote = client.psu
        elif name == "engpsu":
            remote = client.engpsu

        token = remote.authorize_access_token()

    except Exception as e:
        print("autorize access error =>", e)
        return redirect(url_for("accounts.login"))

    session["oauth_provider"] = name
    return oauth2.handle_authorized_oauth2(remote, token)


@module.route("/logout")
@login_required
def logout():
    name = session.get("oauth_provider")
    logout_user()
    session.clear()

    client = oauth2.oauth2_client
    remote = None
    logout_url = None
    if name == "google":
        remote = client.google
        logout_url = f"{ remote.server_metadata.get('end_session_endpoint') }?redirect={ request.scheme }://{ request.host }"
    elif name == "facebook":
        remote = client.facebook
    elif name == "line":
        remote = client.line
    elif name == "psu":
        remote = client.psu
        logout_url = f"{ remote.server_metadata.get('end_session_endpoint') }"
        if not logout_url:
            logout_url = current_app.config.get("PSU_END_SESSION")
    elif name == "engpsu":
        remote = client.engpsu

    if logout_url:
        return redirect(logout_url)

    return redirect(url_for("site.index"))


@module.route("/accounts")
@login_required
def index():
    user = current_user
    if request.args.get("user"):
        user_id = request.args.get("user")
        user = models.User.objects.get(id=user_id)
    return render_template("/accounts/index.html", user=user)


@module.route("/accounts/edit-profile", methods=["GET", "POST"])
@login_required
def edit_profile():
    form = forms.accounts.AccountForm(
        obj=current_user,
    )
    if not form.validate_on_submit():
        return render_template("/accounts/edit-profile.html", form=form)

    user = current_user._get_current_object()
    user.first_name = form.first_name.data
    user.last_name = form.last_name.data
    user.first_name_th = form.first_name_th.data
    user.last_name_th = form.last_name_th.data
    user.id_card_number = form.id_card_number.data
    if not user.gave_informations:
        user.gave_informations = True
    user.save()

    return redirect(url_for("accounts.index"))


@module.route(
    "/accounts/identities/add", methods=["GET", "POST"], defaults={"index": -1}
)
@module.route("/accounts/identities/<int:index>/edit", methods=["GET", "POST"])
@login_required
def add_or_edit_identity(index):
    user = current_user

    form = forms.admin.users.IdentityForm()
    if request.method == "GET" and index >= 0:
        form = forms.admin.users.IdentityForm(obj=user.identities[index])

    if not form.validate_on_submit():
        return render_template(
            "administration/users/add-edit-identity.html",
            form=form,
        )

    identity = models.Identity()
    if index >= 0:
        identity = user.identities[index]

    form.populate_obj(identity)
    identity.added_with = "web"
    identity.added_by = str(current_user.id)
    identity.updated_date = datetime.datetime.now()

    if index < 0:
        is_found = False
        for idr in user.identities:
            if idr.identifier == form.identifier.data:
                is_found = True
                break
        if not is_found:
            user.identities.append(identity)

    user.save()

    pichayon_client.update_member(user=user)

    return redirect(url_for("accounts.index"))

pichayon/web/views/applications.py
import datetime

from flask import (
    Blueprint,
    current_app,
    render_template,
    url_for,
    redirect,
    request,
    session,
)

from flask_login import login_user, logout_user, login_required, current_user
from pichayon import models
from .. import forms
from .. import views
from .. import acl

module = Blueprint("applications", __name__, url_prefix="/applications")


@module.route("/")
@login_required
def index():
    user = current_user._get_current_object()
    applications = models.Application.objects(user=user).order_by("-created_date")
    return render_template("/applications/index.html", applications=applications)


@module.route("/apply", methods=["GET", "POST"])
@login_required
def apply():
    lecturers = models.User.objects(roles="lecturer")
    form = forms.applications.ApplicationForm()
    form.advisor.queryset = lecturers

    user_group_members = models.UserGroupMember.objects(user=current_user)
    user_groups = []
    [
        user_groups.append(ugm.group)
        for ugm in user_group_members
        if ugm not in user_groups
    ]
    group_authorizations = models.GroupAuthorization.objects(
        status="active", user_group__in=user_groups
    )
    door_groups = [ga.door_group for ga in group_authorizations]

    door_ids = []
    [
        [door_ids.append(d.id) for d in dg.doors if d not in door_ids]
        for dg in door_groups
    ]
    doors = models.Door.objects(id__nin=door_ids)
    form.room.queryset = doors

    if not form.validate_on_submit():
        if request.method == "GET":
            form.ended_date.data = form.started_date.data + datetime.timedelta(
                weeks=52 * 4
            )
        return render_template(
            "/applications/request.html",
            form=form,
        )

    application = models.Application()

    form.populate_obj(application)
    application.user = current_user._get_current_object()

    application.save()

    return redirect(url_for("applications.index"))


@module.route("/approve")
@acl.role_required("lecturer")
def approve():
    user = current_user._get_current_object()
    applications = models.Application.objects(advisor=user).order_by("-id")
    return render_template("/applications/approve.html", applications=applications)


@module.route("/<application_id>/cancel")
@login_required
def cancel(application_id):
    application = models.Application.objects().get(id=application_id)
    application.status = "Canceled"
    application.save()

    return redirect(url_for("applications.index"))


@module.route("/<application_id>/delete")
@login_required
def delete(application_id):
    application = models.Application.objects().get(id=application_id)
    application.delete()

    return redirect(url_for("applications.index"))

pichayon/web/views/site.py
from flask import Blueprint, render_template

module = Blueprint("site", __name__)


@module.route("/")
def index():
    return render_template("/site/index.html")

pichayon/web/templates/base/banner.html
<div class="ui inverted vertical center aligned segment">
    <div class="ui text container">
      <div style="padding-top: 5vh;">
        {#<img width="300px" src="{{ url_for('static', filename='images/lotus-500px.png') }}"#}
        <i class="ui icon vihara massive" ></i>
      </div> 
       <h1 class="ui huge inverted header" style="font-size:4em">{{ config.get('APP_TITLE') }} </h1>
      <h2>Pichayon Door Management System, Please Login.</h2>
      <div style="padding-top: 20px;">
        <a href="{{ url_for('accounts.login') }}" class="ui huge primary button"><i class="signup icon"></i>Login</a>
      </div>
      <div style="padding: 5vh;">
      </div>
    </div>
</div>

pichayon/web/templates/base/base-layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title>{% block title  %}{{ config.get('APP_TITLE') }}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='node_modules/fomantic-ui-css/semantic.min.css') | add_date_url}}">
    <script src="{{ url_for('static', filename='node_modules/jquery/dist/jquery.min.js') | add_date_url}}"></script>
    <script src="{{ url_for('static', filename='node_modules/fomantic-ui-css/semantic.min.js') | add_date_url}}"></script>
    <script src="{{ url_for('static', filename='node_modules/brython/brython.js') | add_date_url}}"></script>
    <script src="{{ url_for('static', filename='node_modules/brython/brython_stdlib.js') | add_date_url}}"></script>

    <style type="text/css">
      body {
        background-color: #DADADA;
      }
    </style>
    
    {% block default_head %}{% endblock %}
    {% block additional_head %}{% endblock %}
  </head>

  <body onload="brython()">
    {% block body %}{% endblock %}
  </body>
	{% block additional_js %}{% endblock %}
</html>

pichayon/web/templates/base/default-dashboard.html
{% extends "/base/base-layout.html" %}

{% block title %}{{ config.get('APP_TITLE') }} Dashboard{% endblock %}

{% block default_head %}
  <style type="text/css">
    .ui.main.menu {
      display: none;
    }

    .full.height {
      display: flex;
      flex-direction: row;
    }

    .full.height > .toc .ui.menu {
      border-radius: 0;
      border-width: 0 1px 0 0;
      margin: 0;
      width: inherit;
      max-height: 100vh;
      height: 100vh;
      overflow: auto;
    }

    .toc {
      position: fixed;
      z-index: 1;
      width: 250px;
      flex: 0 0 auto;
      background-color: #1b1c1d;
    }

    .article {
      flex: 1 1 auto;
      min-width: 0px;
      margin-left: 250px;
    }

    .footer {
      border-top: 1px solid #DDDDDD !important;
      box-shadow: 0px 2px 3px rgba(0, 0, 0, 0.08) inset !important;
      background-color: #FAFAFA !important;
      margin-top: 30px !important;
    }

    .main-content {
      margin: 20px !important;
      margin-top: 20px;
      min-height: 70vh;
    }

    .introduction {
      margin-left: 20px !important;
      border-bottom: 1px solid #DDDDDD;
      padding-bottom: 10px !important;
    }

    
    @media only screen and (max-width: 1050px) {
      .toc {
        display: none !important;
      }
      
      .article {
        margin-left: 0px;
      }

      .ui.main.menu {
        display: block !important;
      }
      .introduction {
        display: none !important;
      }
      .fixed.menu > .container {
        width: 100%; !important;
    }

  </style>

  <script type="text/javascript">
  $(document)
  .ready(function() {

      $('.left.sidebar.menu')
        .sidebar('attach events', '.launch.icon.item', 'show')
      ;
      $('.launch.icon.item')
        .removeClass('disabled')
      ;
 
    })
  ;
  </script>

{% endblock default_head %}


{% block body %}
{# begin slide menu #}
<div class="ui vertical inverted sidebar large menu left">
   {% include "/base/menu-dashboard.html" with context %}
</div>
{# end slide menu #}

{# begin top bar mobile #}
<div class="ui fixed inverted main menu">
  <div class="ui container">
    <a class="launch icon item">
      <i class="content icon"></i>
    </a>

    <div class="item">
      {% block dashboard_title %}Dashboard{% endblock %}
    </div>

    {#
    <div class="right menu">
      
      <div class="vertically fitted borderless item">
        <iframe class="github" src="./Layouts _ Fomantic UI_files/github-btn.html" allowtransparency="true" frameborder="0" scrolling="0" width="100" height="20"></iframe>
      </div>
      
      <div class="item">
        <div class="ui hidden right aligned search input" id="search">
          <div class="ui transparent icon input">
            <input class="prompt" type="text" placeholder="Search...">
            <i class="inverted search link icon" data-content="Search UI"></i>
          </div>
          <div class="results"></div>
        </div>
      </div>

    </div>
    #}
  </div>
</div>
{# end top bar mobile #}

<div class="pusher">
  <div class="full height">

    {# begin default left side toc #}
    <div class="toc">
      <div class="ui vertical inverted large menu">
        {% include "/base/menu-dashboard.html" with context %}
      </div>
    </div>
    {# end default left side toc #}

    {# begin main article #}
    <div class="article">
      <header>
        <div class="ui vertical dividing segment">
          <div class="introduction">
            <h1 class="ui header">
              {{ self.dashboard_title() }}
            </h1>
          </div>
        </div>
      </header>

      <main class="main-content">
        {%- if self.dashboard_title().lower() != 'dashboard' %}
        <div class="ui segment">
          <div class="ui big breadcrumb">
            {% block breadcrumbs %}{% endblock %}
          </div>
        </div>
        {% endif -%}
{% block content %}{% endblock %}
      </main>

      <footer class="ui vertical footer segment">
{% include "/base/footer.html" %}
      </footer>
      
    </div>
    {# end main article #}

  </div>
{#
<footer class="ui vertical footer segment">
{% include "/base/footer.html" %}
</footer>
#}
</div>

{% endblock body %}

pichayon/web/templates/base/default-page.html
{% extends "/base/base-layout.html" %}
{% block body %}
<header>
{% block header %}
  {% include "/base/menu.html" %}
  {% if request.path == '/' %}
    {% include "/base/banner.html" %}
  {% else %}
    <div style="padding-top:50px;"></div>
  {% endif %}
{% endblock %}
</header>

<main style="min-height: 20vh;">
  <div class="container">
    {% block content %}{% endblock content %}
  </div>
</main>

<footer class="ui vertical footer segment" style="padding-top: 2em;">
{% include "/base/footer.html" %}
</footer>
{% endblock %}

pichayon/web/templates/base/error-handler.html
{% macro get_validate_class(errors) -%}
{%- set class_str = '' -%}
{% if errors | count > 0 -%}
{% set class_str = class_str + ' ' + 'error' %}
{%- endif %}
{{- class_str -}}
{%- endmacro %}

{% macro get_error_messages(errors) -%}
	{% if errors %}
  <div class="ui negative message">
    {{ ', '.join(errors) }}
  </div>
  {% endif %}
{%- endmacro %}

pichayon/web/templates/base/footer.html
  <div class="ui container">
    <div class="ui grid">
      <div class="four wide column">
        <h5 class="ui header">Pichayon Door Management System</h5>
        <img width="20%" src="{{ url_for('static', filename='images/r202.png') }}">
        <p>Develop by R202 research lab</p>
      </div>
      <div class="five wide column">
        <h5 class="ui header">Department of Computer Engineering</h5>
        <p>
        Faculty of Engineering<br/>
        Prince of Songkla University<br/>
        Hat Yai, Thailand
        </p>
      </div>
      <div class="seven wide column">
        <h5 class="ui header">Connect</h5>
        <div class="ui link list">
          <a href="http://coe.psu.ac.th">CoE, Eng, PSU</a>
        </div>
      </div>
    </div>
  </div>

pichayon/web/templates/base/html-renderer.html
{% import '/base/error-handler.html' as eh %}

{% macro render_field(field, class_='') -%}
{%- set style = '%s' | format(eh.get_validate_class(field.errors)) -%}
{%- if class_ != '' -%}
{%- set style = '%s %s' | format(class_, eh.get_validate_class(field.errors)) -%}
{%- endif -%}
<div class="field">
{{ field.label }}
{{ field(class_=style) }}
</div>
{{ eh.get_error_messages(field.errors) }}
{%- endmacro %}

{% macro render_checkbox(field) -%}
<div class="field">
  <div class="ui checkbox">
    {{ field }}
    {{ field.label }}
  </div>
</div>
{%- endmacro %}


{% macro render_fileinput(field) -%}
<div class="field">
  {{ field.label }}
  <div class="ui action input">
    <input type="text" placeholder="{{ field.label.text }}" readonly class="attach-file-{{field.name}}">
    {{ field(style="display: none;") }}
    <div class="ui icon button attach-file-{{field.name}}">
      <i class="attach icon"></i>
    </div>
  </div>
</div>
{%- endmacro %}


{% macro render_select_disabled(field) -%}
{{ render_field(field, class_='ui fluid search selection dropdown disabled') }}
{%- endmacro %}

{% macro render_select(field) -%}
{{ render_field(field, class_='ui fluid search selection dropdown') }}
{%- endmacro %}

{% macro render_select_no_search(field) -%}
{{ render_field(field, class_='ui fluid dropdown') }}
{%- endmacro %}

{% macro render_multiple_select(field) -%}
{{ render_field(field, class_='ui fluid search dropdown') }}
{%- endmacro %}



{% macro render_calendar(field, calendar_id='calendar') -%}
<div class="field">
  {{ field.label }}
  <div class="ui calendar" id="{{ calendar_id }}">
    <div class="ui input left icon">
      <i class="calendar icon"></i>
      {{ field(autocomplete='off') }}
    </div>
  </div>
</div>
{%- endmacro %}

{% macro render_timepicker(field, timepicker_id='timepicker') -%}
<div class="field">
  {{ field.label }}
  <div class="ui calendar" id="{{ timepicker_id }}">
    <div class="ui input left icon">
      <i class="time icon"></i>
      {{ field(placeholder='Time') }}
    </div>
  </div>
</div>
{%- endmacro %}


{% macro render_pagination(pagination, endpoint, left_edge=2, left_current=1,right_current=1, right_edge=2) %}
{% if pagination.pages > 1 %}
<div class="ui pagination menu">
  <a class="{{ 'disabled' if not pagination.has_prev }} item"
    href="{{ url_for(endpoint, page=pagination.prev_num) }}"
  ><i class="angle left icon"></i></a>
  {% for page in pagination.iter_pages(left_edge=left_edge, left_current=left_current, right_current=right_current, right_edge=right_edge) %}
  {% if page %}
  {% if page != pagination.page %}
    <a class="item"
    href="{{ url_for(endpoint, page=page) }}">{{ page }}</a>
  {% else %}
    <strong class="active item">
      {{ page }}
    </strong>
  {% endif %}
  {% else %}
    <div class="disabled item">…</div>
  {% endif %}
  {% endfor %}
  <a class="{{ 'disabled' if not pagination.has_next }} item"
  href="{{ url_for(endpoint, page=pagination.next_num) }}"
  ><i class="angle right icon"></i></a>
  </div>
{% endif %}
{% endmacro %}

pichayon/web/templates/base/menu-dashboard.html
<div class="item">
  {%- if current_user.get_image() %}
  <a href="{{ url_for('accounts.index') }}" class="ui image">
    <img class="ui avatar image" src="{{ current_user.get_image() }}">
  </a>
{% endif -%}
  <a href="{{ url_for('accounts.index') }}"><span class="white-text name">{{ current_user.first_name }} {{ current_user.last_name }}</span></a><br/>
  <a href="{{ url_for('accounts.index') }}"><span class="white-text email">{{ current_user.email }}</span></a>
</div>

<a class="item" href="{{ url_for('dashboard.index') }}"><i class="icon dashboard"></i>Dashboard</a>

{% if current_user.has_roles('lecturer') %}
<a class="item" href="{{ url_for('applications.approve') }}"><i class="list alternate icon"></i>Applications Approval</a>
{% endif %}

{% if current_user.has_roles('admin') %}
  <a class="item" href="{{ url_for('administration.doors.index') }}"><i class="door closed icon"></i>Door Manager</a>
  <a class="item" href="{{ url_for('administration.door_groups.index') }}"><i class="landmark icon"></i>Door Groups</a>
  <a class="item" href="{{ url_for('administration.user_groups.index') }}"><i class="group closed icon"></i>User Groups</a>
  <a class="item" href="{{ url_for('administration.authorizations.index') }}"><i class="user shield icon"></i>Authorization</a>
  <a class="item" href="{{ url_for('administration.history_logs.index') }}"><i class="history closed icon"></i>History Log</a>
  <a class="item" href="{{ url_for('administration.users.index') }}"><i class="users icon"></i>Users</a>
  
  <a class="item" href="{{ url_for('administration.applications.index') }}"><i class="list alternate icon"></i>Admin Applications Approval</a>
{% endif %}

<a class="item" href="{{ url_for('applications.index') }}"><i class="address card icon"></i>Door Application</a>
<a class="item" href="{{ url_for('accounts.index') }}"><i class="user card icon"></i>Account</a>
<a class="item" href="{{ url_for('accounts.logout') }}"><i class="icon sign out"></i>Logout</a>

pichayon/web/templates/base/menu.html
<div class="ui fixed inverted menu">
  <div class="ui container">
    <a href="{{ url_for('site.index') }}" class="header item">
      {# <img class="logo" src="{{ url_for('static', filename='images/sadhu.png') }}"> #}
      <i class="ui icon vihara"></i>
      <span style="padding-left:10px;">
        {{ config['APP_TITLE'] }}
      </span>
    </a>
    {#
    <a href="{{ url_for('dashboard.index') }}" class="item">Dashboard</a>
    <div class="ui simple dropdown item">
      Dropdown <i class="dropdown icon"></i>
      <div class="menu">
        <a class="item" href="#">Link Item</a>
        <a class="item" href="#">Link Item</a>
        <div class="divider"></div>
        <div class="header">Header Item</div>
        <div class="item">
          <i class="dropdown icon"></i>
          Sub Menu
          <div class="menu">
            <a class="item" href="#">Link Item</a>
            <a class="item" href="#">Link Item</a>
          </div>
        </div>
        <a class="item" href="#">Link Item</a>
      </div>
    </div>
    #}
    <div class="right menu">
      {#
      <div class="item">
        <div class="ui transparent inverted icon input">
          <i class="search icon"></i>
          <input type="text" placeholder="Search">
        </div>
      </div>
      #}
    {% if current_user.is_authenticated %}
      <a class="item" href="{{ url_for('dashboard.index') }}">Dashboard</a>
      <a class="item" href="{{ url_for('accounts.logout') }}">Logout</a>
    {% else %}
      <a class="item" href="{{ url_for('accounts.login') }}">Login</a>
    {% endif %}

    </div>
  </div>
</div>
<div style="padding-top: 40px;"> </div>