pichayon/web/forms/applications.py
from wtforms import Form, fields, validators
from pichayon import models

import datetime

from flask_wtf import FlaskForm
from wtforms import widgets
from flask_mongoengine.wtf import model_form

BaseApplicationForm = model_form(
    models.Application,
    FlaskForm,
    exclude=["users", "status", "created_date", "approved_date"],
    field_args={
        "degree": {"label": "Degrees"},
        "advisor": {
            "label": "Advisor",
            "label_modifier": lambda ad: f"{ad.first_name} {ad.last_name}",
        },
        "started_date": {"label": "Start Date", "format": "%Y-%m-%d %H:%M"},
        "ended_date": {"label": "End Date", "format": "%Y-%m-%d %H:%M"},
        "room": {"label": "Room", "label_modifier": lambda r: r.name},
        "purpose": {"label": "Purpose"},
        "request_checkbox": {"label": "ยอมรับนโยบายการเข้าใช้งานสถานที่"},
    },
)


class ApplicationForm(BaseApplicationForm):
    pass


BaseApplicationRemarkForm = model_form(
    models.Application,
    FlaskForm,
    only=["remark"],
    field_args={"remark": {"label": "Remark"}},
)


class ApplicationRemarkForm(BaseApplicationRemarkForm):
    pass


class UserGroupMemberFromApplicationForm(FlaskForm):
    user_groups = fields.SelectMultipleField(
        "User Group",
        validators=[validators.InputRequired()],
    )

    role = fields.SelectField(
        "Role",
        validators=[validators.InputRequired()],
        default="member",
        choices=[("member", "Member"), ("admin", "Admin")],
    )

    started_date = fields.DateTimeField(
        "Started Date",
        format="%Y-%m-%d %H:%M",
        default=datetime.date.today(),
        widget=widgets.TextInput(),
    )
    expired_date = fields.DateTimeField(
        "Expired Date",
        format="%Y-%m-%d %H:%M",
        validators=[validators.Optional()],
        widget=widgets.TextInput(),
    )

pichayon/web/views/applications.py
import datetime

from flask import (
    Blueprint,
    current_app,
    render_template,
    url_for,
    redirect,
    request,
    session,
)

from flask_login import login_user, logout_user, login_required, current_user
from pichayon import models
from .. import forms
from .. import views
from .. import acl

module = Blueprint("applications", __name__, url_prefix="/applications")


@module.route("/")
@login_required
def index():
    user = current_user._get_current_object()
    applications = models.Application.objects(user=user).order_by("-created_date")
    return render_template("/applications/index.html", applications=applications)


@module.route("/apply", methods=["GET", "POST"])
@login_required
def apply():
    lecturers = models.User.objects(roles="lecturer")
    form = forms.applications.ApplicationForm()
    form.advisor.queryset = lecturers

    user_group_members = models.UserGroupMember.objects(user=current_user)
    user_groups = []
    [
        user_groups.append(ugm.group)
        for ugm in user_group_members
        if ugm not in user_groups
    ]
    group_authorizations = models.GroupAuthorization.objects(
        status="active", user_group__in=user_groups
    )
    door_groups = [ga.door_group for ga in group_authorizations]

    door_ids = []
    [
        [door_ids.append(d.id) for d in dg.doors if d not in door_ids]
        for dg in door_groups
    ]
    doors = models.Door.objects(id__nin=door_ids)
    form.room.queryset = doors

    if not form.validate_on_submit():
        if request.method == "GET":
            form.ended_date.data = form.started_date.data + datetime.timedelta(
                weeks=52 * 4
            )
        return render_template(
            "/applications/request.html",
            form=form,
        )

    application = models.Application()

    form.populate_obj(application)
    application.user = current_user._get_current_object()

    application.save()

    return redirect(url_for("applications.index"))


@module.route("/approve")
@acl.role_required("lecturer")
def approve():
    user = current_user._get_current_object()
    applications = models.Application.objects(advisor=user).order_by("-id")
    return render_template("/applications/approve.html", applications=applications)


@module.route("/<application_id>/cancel")
@login_required
def cancel(application_id):
    application = models.Application.objects().get(id=application_id)
    application.status = "Canceled"
    application.save()

    return redirect(url_for("applications.index"))


@module.route("/<application_id>/delete")
@login_required
def delete(application_id):
    application = models.Application.objects().get(id=application_id)
    application.delete()

    return redirect(url_for("applications.index"))

pichayon/web/templates/applications/approve.html
{% extends 'base/default-dashboard.html'%}

{% block dashboard_title%}
Room Application
{% endblock %}

{% block breadcrumbs %}
<a href="{{ url_for('applications.index')}}" class="section">Application Lists</a>
{% endblock %}

{% block content %}

<div class="'ui content">
    <div class='ui segment'>

        <div>
            <a class="ui primary button" href="{{ url_for('applications.apply')}}">
                Create Application
            </a>
        </div>

        <table class="ui celled table">
            <thead>
                <tr>
                    <th>ID Number - Name</th>
                    <th>Degree</th>
                    <th>Advisor</th>
                    <th>Room</th>
                    <th>Request Date</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Purpose</th>
                    <th>Remark</th>
                    <th>Status</th>
                    <th>Cancel</th>
                </tr>
            </thead>
            <tbody>
                <tr>

                    {% for application in applications %}

                    <td data-label="Name">
                        {{ application.user.id_card_number }} {{ application.user.first_name }} {{
                        application.user.last_name }}
                    </td>
                    <td data-label="Degree">
                        {{ application.degree }}
                    </td>
                    <td data-label="Advisor">
                        {{ application.advisor.first_name }} {{ application.advisor.last_name }}
                    </td>
                    <td data-label="Room">
                        {{ application.room.name }}
                    </td>
                    <td data-label="Request Date">
                        {{ application.created_date }}
                    </td>
                    <td data-label="Start Date">
                        {{ application.started_date }}
                    </td>
                    <td data-label="End Date">
                        {{ application.ended_date }}
                    </td>
                    <td data-label="Purpose">
                        {{ application.purpose }}
                    </td>
                    <td data-label="Remark">
                        {{ application.remark}}
                    </td>
                    <td data-label="Status">
                        {{ application.status }}
                    </td>

                    <td class="single line">
                        {% if application.status != "approved" %}
                        <a class="ui primary icon button"
                            href="{{ url_for('administration.applications.add_or_edit_user_to_user_group', application_id=application.id) }}">
                            <i class="check icon"></i>
                        </a>
                        <a class="ui red icon button"
                            href="{{ url_for('applications.delete', application_id=application.id) }}">
                            <i class="times icon"></i>
                        </a>
                        {% else %}
                        <a class="ui gray icon button" style="pointer-events: none;">
                            <i class="check icon"></i>
                        </a>
                        <a class="ui gray icon button" style="pointer-events: none;">
                            <i class="times icon"></i>
                        </a>
                        {% endif %}
                    </td>
                </tr>
            </tbody>
            <tfoot>
    </div>
    </th>
    </tr>
    {% endfor %}
    </table>



    {% endblock %}

pichayon/web/templates/applications/index.html
{% extends 'base/default-dashboard.html'%}

{% block dashboard_title%}
Room Application
{% endblock %}

{% block breadcrumbs %}
<a href="{{ url_for('applications.index')}}" class="section">Application Lists</a>
{% endblock %}

{% block content %}

<div class="'ui content">
    <div class='ui segment'>

        <div>
            <a class="ui primary button" href="{{ url_for('applications.apply')}}">
                Create Application
            </a>
        </div>

        <table class="ui celled table">
            <thead>
                <tr>
                    <th>ID Number - Name</th>
                    <th>Degree</th>
                    <th>Advisor</th>
                    <th>Room</th>
                    <th>Request Date</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Purpose</th>
                    <th>Remark</th>
                    <th>Status</th>
                    <th>Cancel</th>
                </tr>
            </thead>
            <tbody>
                {% for application in applications %}
                <tr>
                    <td data-label="Name">
                        {{ application.user.id_card_number }} {{ application.user.first_name }} {{
                        application.user.last_name }}
                    </td>
                    <td data-label="Degree">
                        {{ application.degree }}
                    </td>
                    <td data-label="Advisor">
                        {{ application.advisor.first_name }} {{ application.advisor.last_name }}
                    </td>
                    <td data-label="Room">
                        {{ application.room.name }}
                    </td>
                    <td data-label="Request Date">
                        {{ application.created_date.strftime("%Y-%m-%d %H:%M") }}
                    </td>
                    <td data-label="Start Date">
                        {{ application.started_date.strftime("%Y-%m-%d %H:%M") }}
                    </td>
                    <td data-label="End Date">
                        {{ application.ended_date.strftime("%Y-%m-%d %H:%M") }}
                    </td>
                    <td data-label="Purpose">
                        {{ application.purpose }}
                    </td>
                    <td data-label="Remark">
                        {{ application.remark if application.remark }}
                    </td>
                    <td data-label="Status">
                        {{ application.status }}
                    </td>
                    <td class="single line">
                        {% if application.status == "pending" %}
                        <a class="ui red icon button"
                            href="{{ url_for('applications.delete', application_id=application.id) }}">
                            <i class="times icon"></i>
                        </a>
                        {% else %}
                        <div class="ui gray icon button" style="pointer-events: none;">
                            <i class="times icon"></i>
                        </div>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

pichayon/web/templates/applications/request.html
{% extends 'applications/index.html'%}
{% import '/base/html-renderer.html' as renderer%}

{% block dashboard_title%}
Create Apply
{% endblock %}

{% block breadcrumbs %}
<div class="ui breadcrumb">
    <a href="{{ url_for('applications.index')}}" class="section">Application Lists</a>
    <i class="right angle icon divider"></i>
    <a  class="section">Create Apply</a>
</div>
{% endblock %}

{% block content %}
    <div class="ui content">
        <div class="ui segment">
            <form class="ui form" method="POST">

                {{ form.hidden_tag() }}

                {{ renderer.render_select(form.room) }}

                {{ renderer.render_select(form.degree) }}

                {{ renderer.render_select(form.advisor) }}

                {{ renderer.render_field(form.purpose) }}


                <div class="two fields">

                    {{ renderer.render_calendar(form.started_date, calendar_id = "started_date_calendar") }}

                    {{ renderer.render_calendar(form.ended_date, calendar_id = "ended_date_calendar") }}

                </div>
                    {{ renderer.render_checkbox(form.request_checkbox) }}
                <div>
                    <button class="ui primary button" type="submit">Create</button>
                </div>
                
            </form>

        </div>
    </div>
{% endblock %}

{% block additional_js %}
<script type="text/javascript">
$('.selection.dropdown').dropdown();
</script>

<script type="text/javascript">
  datetime_formatter = {
    datetime: function (datetime, settings) {
        if (!datetime) return '';
        var day = datetime.getDate();
        var month = datetime.getMonth() + 1;
        var year = datetime.getFullYear();
        var hour = datetime.getHours();
        var minute = datetime.getMinutes();
        return year + '-' + ("0" + month).slice(-2) + '-' + ("0" + day).slice(-2) + " " + ("0" + hour).slice(-2) + ":" + ("0" + minute).slice(-2)  ;
    }
};
var calendar_setting = {
type: 'datetime',
monthFirst: false,
formatter: datetime_formatter,
today: true,
ampm: false,
text: {
    days: ['อา', 'จ', 'อ', 'พ', 'พฤ', 'ศ', 'ส'],
    months: ['มกราคม', 'กุมภาพันธ์', 'มีนาคม', 'เมษายน', 'พฤษภาคม', 'มิถุนายน', 'กรกฎาคม', 'สิงหาคม', 'กันยายน', 'ตุลาคม', 'พฤษจิกายน', 'ธันวาคม'],
    monthsShort: ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'],
    today: 'วันนี้',
    now: 'ปัจจุบัน',
    am: 'AM',
    pm: 'PM'
},
};
$('#started_date_calendar').calendar(calendar_setting);
$('#ended_date_calendar').calendar(calendar_setting);
</script>
{% endblock %}